### ISSUE TITLE
How do use this?

### ISSUE THREAD

**Issue by aayush27894** [royinx/CUDA_Resize#2] opened 2021-03-03 09:05 UTC
Could you please guide me as to how I could use this in my python function without having to use docker. I am currently using PIL for image processing. The pillow package is slowing down my code. Most of the time is spent is resizing and is being done on CPU.

**Comment by royinx** [comment] 2021-03-04 14:28
First of all, I hv to notice you this script has its pros and cons,
I make used with the GPU but limited by bandwidth transfer.
A bottleneck raised in memory copy between host and device, 

This function I was designed for TensorRT, high speed inference, which hv python API to access the GPU memory directly.
if you wanna plug this to the framework like TF, Pytorch , MXNet which might cause the CUDA stream conflict (hvnt test yet), also the unnecessary data transfer.

```
my flow: CPU -> DRAM -> GPU VRAM -> process -> TensorRT -> DRAM -> VRAM

open cv : CPU -> DRAM -> GPU VRAM -> process -> GPU VRAM -> DRAM -> Framework(TF,Pytorch) -> DRAM -> VRAM

unnecessary: CPU -> DRAM -> GPU VRAM -> process -> GPU VRAM -> DRAM -> Framework(TF,Pytorch) -> DRAM -> VRAM
```

Transfer between VRAM and DRAM is very **expensive**, if u want the third method, you may disappointed, most of the case, opencv function works better with my repo.

this problem will be solve two years laters by AMD Smart Access Memory (SAM), they share this with Nvidia, 
Nvidia may support in next generation GPU and driver.

--------- 

** **BUT** ** you can still try out both method
I hv tested out, up scaling probably cuResize working better than openCV.

Run demo code in cuResize.py, 

also this is a good question for me to remaster the repo for non CUDA programmer

I may create a new repo and pack this as python library when I have time. 

free to ask if you have any question

**Comment by royinx** [comment] 2021-05-25 06:27
Since there are no update more than 3 weeks, i will close this issue
free to reopen if you have any questions.

**Closed as completed by royinx** 2021-05-25 06:27 UTC
